#!/bin/sh

GIT_DIR="$HOME"/Downloads/git

echo "Did you modify /etc/makepkg.conf? [y/n]" 
read -r input

case "$input" in
	y)
		echo "The script will now proceed"
		;;
	n)
		echo "Go edit /etc/makepkg.conf to compile packages faster. Exiting program..."
		exit 1
		;;
	*)
		echo "Invalid input. Exiting program..."
		exit 1
		;;
esac

mkdir -p "$GIT_DIR"

git clone https://aur.archlinux.org/paru.git "$GIT_DIR"
cd "$HOME"/Downloads/git/paru || exit
makepkg -si
cd "$HOME" || exit

echo "Installing packages..."

paru -S udunits freetube-bin protontricks pandoc-bin pandoc-crossref-bin shellcheck-bin rstudio-desktop-bin nwg-look-bin gruvbox-dark-gtk gruvbox-dark-icons-gtk wlogout xcursor-breeze
