#!/bin/sh

sudo pacman -S git xdg-user-dirs gvfs htop neofetch steam keepassxc ripgrep npm man man-db firefox stow thunderbird rsync marksman helix neovim jq yq qt5ct qt6ct kvantum zathura zathura-pdf-poppler texlive-latexrecommended texlive-xetex mpv newsboat grim swayimg slurp clang pulsemixer

xdg-user-dirs-update
