#!/bin/sh

sudo pacman -S git xdg-user-dirs gvfs htop neofetch steam keepassxc ripgrep npm man man-db firefox stow thunderbird rsync marksman helix neovim jq yq qt5ct qt6ct kvantum

xdg-user-dirs-update
